name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./my_first_contract_front_end

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup yarn
        run: npm install -g yarn

      - name: Debug working directory
        run: |
          echo "Current directory: $(pwd)"
          ls -la  # Optional: List files in the directory
    
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build project
        run: npm run build
      
      - name: Debug after build
        run: |
          echo "Current directory: $(pwd)"
          ls -la  # Optional: List files in the directory
          cd ./dist
          echo "Current directory: $(pwd)"
          ls -la  # Optional: List files in the directory

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    defaults:
      run:
        working-directory: ./my_first_contract_front_end

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
